name: main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # node 编译
      - name: build
        uses: actions/setup-node@v4
      - run: |
          npm i -g hexo-cli
          npm i
          hexo clean
          hexo g

      # docker build，并push
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: registry.cn-shanghai.aliyuncs.com
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: registry.cn-shanghai.aliyuncs.com/my_hb/my-blog:${{ github.sha }}

      # 让K8s应用deployment
      - run: |
          sed -i 's/{TAG}/${{ github.sha }}/g' deployment.yaml
#      - name: deploy to cluster
#        uses: steebchen/kubectl@master
#        with:
#          config: ${{ secrets.KUBE_CONFIG_DATA }}
##          command: apply -f deployment.yaml
#          command: set image --record deployment/blog container=${{ github.repository }}:${{ github.sha }}
#      - name: verify deployment
#        uses: steebchen/kubectl@master
#        with:
#          config: ${{ secrets.KUBE_CONFIG_DATA }}
#          command: rollout status -n blog deployment/blog
      - name: Set up kubectl
        env:
          K3S_KUBECONFIG: ${{ secrets.K3S_KUBECONFIG }}
        # 验证kubectl能否连接到集群
        run: |
          mkdir -p ~/.kube  
          echo "K3S_KUBECONFIG" > ~/.kube/config  
          kubectl cluster-info

      # 部署你的Kubernetes资源
      # 使用你的Deployment YAML文件
      - name: Deploy to K3s
        run: |
          kubectl apply -f deployment.yaml

      # （可选）添加其他验证步骤
      - name: Verify deployment
        # 或其他验证命令来检查部署是否成功
        run: |
          kubectl get pods