name: main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # node 编译
      - name: build
        uses: actions/setup-node@v4
      - run: |
          npm i -g hexo-cli
          npm i
          hexo clean
          hexo g

      # docker build，并push
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: registry.cn-shanghai.aliyuncs.com
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: registry.cn-shanghai.aliyuncs.com/my_hb/my-blog:${{ github.sha }}

      # 让K8s应用deployment
      - name: replace deployment env
        run: |
          sed -i 's/{TAG}/${{ github.sha }}/g' deployment.yaml
      - name: deploy to cluster
        uses: steebchen/kubectl@master
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          command: apply -f deployment.yaml
      - name: verify deployment
        uses: steebchen/kubectl@master
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          command: rollout status -n blog deployment/blog